# Generated by Django 3.2.5 on 2021-07-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='supervising_teacher',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='supervising_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
    ]
