# Generated by Django 3.2.5 on 2021-07-29 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0004_principalteacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.school",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="subject",
            field=models.ManyToManyField(
                blank=True, null=True, to="school.SchoolSubject"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
