# Generated by Django 3.2.5 on 2021-08-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_alter_schoolsubject_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teacher",
            ),
        ),
    ]
